services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:              # 開発用
      - ./frontend:/app   # 開発用
      - /app/node_modules # 開発用
    stdin_open: true      # 開発用　必要に応じてインタラクティブモードを有効にします
    tty: true             # 開発用　コンテナが終了しないようにするための設定

  backend:
    build:
      context: ./backend
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h ${DB_HOST} -u ${DB_USER} --password=${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
      - ./my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h ${DB_HOST} -u ${DB_USER} --password=${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: