name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file for frontend
      run: |
        echo REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} >> ./frontend/.env
        echo WEB_URL=${{ secrets.WEB_URL }} >> ./frontend/.env

    - name: Create .env file for backend
      run: |
        echo WEB_URL=${{ secrets.WEB_URL }} >> ./backend/.env
        echo DB_HOST=${{ secrets.DB_HOST }} >> ./backend/.env
        echo DB_USER=${{ secrets.DB_USER }} >> ./backend/.env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> ./backend/.env
        echo DB_NAME=${{ secrets.DB_NAME }} >> ./backend/.env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: dockerHubUser/app-frontend:latest  #自身の名称に変更

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: dockerHubUser/app-backend:latest  #自身の名称に変更

    - name: Log out from DockerHub
      run: docker logout
